### PR TITLE
fix: Use realpath to find script absolute path (Fixes #7)

### LINKED ISSUE #7: Use realpath to find SCRIPT_DIR
Detect the `phototimer-images-to-mp4.sh` script's path using `dirname` & `realpath` on `$0`

### PR DESCRIPTION
**Pull request by trinitronx**

### CODE REVIEW

File: phototimer-images-to-mp4.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@
 ### License: see the LICENSE file
 ###
 SCRIPT="$0"
-SCRIPT_DIR="$(dirname $SCRIPT)"
+SCRIPT_DIR="$(dirname $(realpath $SCRIPT))"
```
Comment (trinitronx) [inline phototimer-images-to-mp4.sh:10]: :+1:
